In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [5]:
def split_scalar(X,y):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train,X_test,y_train, y_test

In [6]:
def perform_lda(indpen_X,dep_Y,n):
    lda = LDA(n_components = n)
    X_train = lda.fit_transform(indpen_X,dep_Y)
    return lda, X_train

In [7]:
def logistic(X_train, y_train,X_test):
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return cm,accuracy,classifier

def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Navie(X_train,y_train,X_test):

    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def knn(X_train,y_train,X_test):

    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Decision(X_train,y_train,X_test):

    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def random(X_train,y_train,X_test):

    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def cm_predition (classifier,X_test):
    y_pred = classifier.predict(X_test)
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred)
    from sklearn.metrics import accuracy_score
    accuracy= accuracy_score(y_test, y_pred)
    return cm,accuracy,classifier

In [8]:
def lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand):
    dataframe=pd.DataFrame(index=['LDA n=2'],columns=['Logistic','SVMlin','SVMNL','Navie','KNN','DT','RF'])
    for number,index in enumerate(dataframe.index):
        dataframe['Logistic'][index]=acclog[number]
        dataframe['SVMlin'][index]=accsvmlin[number]
        dataframe['SVMNL'][index]=accsvmnl[number]
        dataframe['Navie'][index]=accnav[number]
        dataframe['KNN'][index]=accknn[number]
        dataframe['DT'][index]=accdec[number]
        dataframe['RF'][index]=accrand[number]
    return dataframe

In [9]:
dataset1 = pd.read_csv("preprocessed-Flipkart Mobile.csv", index_col=None)
df2 = dataset1
df2 = pd.get_dummies(df2, drop_first=True)

indpen_X = df2.drop('sales_price', axis=1)
dep_Y = df2['sales_price']

In [22]:
lda, X_train_lda =perform_lda(indpen_X,dep_Y,6) 
# n_components set to 1 for binary classification
# created a empty list to append the final value
acclog=[]
accsvmlin=[]
accsvmnl=[]
accnav=[]
accknn=[]
accdec=[]
accrand=[]

In [23]:
X_train, X_test, y_train, y_test=split_scalar(X_train_lda,dep_Y)

cm,accuracy,classifier=logistic(X_train,y_train,X_test)
acclog.append(accuracy)

cm,accuracy,classifier=svm_linear(X_train,y_train,X_test)
accsvmlin.append(accuracy)

cm,accuracy,classifier=svm_NL(X_train,y_train,X_test)
accsvmnl.append(accuracy)

cm,accuracy,classifier=Navie(X_train,y_train,X_test)
accnav.append(accuracy)

cm,accuracy,classifier=knn(X_train,y_train,X_test)
accknn.append(accuracy)

cm,accuracy,classifier=Decision(X_train,y_train,X_test)
accdec.append(accuracy)

cm,accuracy,classifier=random(X_train,y_train,X_test)
accrand.append(accuracy)
    
result =lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][index]=acclog[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMlin'][index]=accsvmlin[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMNL'][index]=accsvmnl[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Navie'][index]=accnav[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['KNN'][index]=accknn[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['DT'][index]=accdec[number]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11480\2702623332.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['RF'][index]=accrand[number]

In [12]:
result # 1

         Logistic    SVMlin     SVMNL     Navie       KNN        DT        RF
LDA n=2  0.139535  0.209302  0.255814  0.523256  0.488372  0.627907  0.616279

In [15]:
result # 3

        Logistic    SVMlin     SVMNL     Navie       KNN        DT        RF
LDA n=2  0.27907  0.383721  0.313953  0.604651  0.627907  0.790698  0.802326

In [18]:
result # 4

         Logistic   SVMlin     SVMNL     Navie       KNN       DT        RF
LDA n=2  0.348837  0.55814  0.360465  0.616279  0.651163  0.77907  0.813953

In [21]:
result # 5

         Logistic    SVMlin     SVMNL     Navie       KNN        DT        RF
LDA n=2  0.406977  0.593023  0.430233  0.627907  0.674419  0.732558  0.813953

In [24]:
result # 6

         Logistic    SVMlin     SVMNL     Navie       KNN        DT       RF
LDA n=2  0.476744  0.674419  0.430233  0.627907  0.651163  0.744186  0.77907